# Generated by Django 4.1.4 on 2023-01-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0004_alter_basket_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="stripe_product_price_id",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
